### ISSUE TITLE
Modrinth Support

### ISSUE THREAD

**Issue by Sylencia** [MukiTanuki/name_formatting_station#2]
I've been trying to consolidate my mod and pack downloads onto Modrinth, and am wondering if there's any plans to upload it there?

**Comment by MukiTanuki** [comment]
at some point most likely.

**Comment by MukiTanuki** [comment]
I've added projects for most of my current datapacks on modrinth:
https://modrinth.com/user/MukiTanuki
https://modrinth.com/datapack/name-formatting-station-datapack
